version: "3.8"

services:
  cans-server:
    build:
      context: .
      target: server
    container_name: ${CANS_SERVER_HOSTNAME}
    command: python -u -m server
    env_file:
      - .env
    networks:
      - cans-network
    ports:
      - ${CANS_PORT}:${CANS_PORT}
    volumes:
      - ./log:/log

  cans-echo-service:
    build:
      context: .
      target: client_echo
    container_name: cans-echo-service
    depends_on:
      - cans-server
    command: python -u -m client.echo_client
    env_file:
      - .env
    networks:
      - cans-network

  cans-echo-eve:
    build:
      context: .
      target: client_echo
    container_name: cans-echo-eve
    depends_on:
      - cans-server
    command: python -u -m client.echo_client eve_key
    env_file:
      - .env
    networks:
      - cans-network

  cans-echo-bob:
    build:
      context: .
      target: client_echo
    container_name: cans-echo-bob
    depends_on:
      - cans-server
    command: python -u -m client.echo_client bob_key
    env_file:
      - .env
    networks:
      - cans-network

networks:
  cans-network:
    name: cans-network
    driver: bridge
