version: "3.8"

services:
  cans-server:
    build:
      context: .
      target: server_dev
    container_name: ${CANS_SERVER_HOSTNAME}
    command: python -u ./server.py
    env_file:
      - .env
    networks:
      - cans-network
    ports:
      - ${CANS_PORT}:${CANS_PORT}

  cans-client:
    build:
      context: .
      target: client_dev
    container_name: cans-client
    depends_on:
      - cans-server
    command: python -u ./client.py
    env_file:
      - .env
    networks:
      - cans-network

networks:
  cans-network:
    name: cans-network
    driver: bridge
