version: "3.8"

services:
  cans-server:
    build:
      context: .
      target: server
    container_name: ${CANS_SERVER_HOSTNAME}
    command: python -u -m server
    env_file:
      - .env
    networks:
      - cans-network
    ports:
      - ${CANS_PORT}:${CANS_PORT}
    volumes:
      - ./log:/log

  cans-client-alice:
    build:
      context: .
      target: client_dev
    container_name: cans-client-alice
    depends_on:
      - cans-server
    command: python -u -m client ${CANS_DEV_ALICE_PUBKEY} ${CANS_DEV_BOB_PUBKEY}
    env_file:
      - .env
    networks:
      - cans-network

  cans-client-bob:
    build:
      context: .
      target: client_dev
    container_name: cans-client-bob
    depends_on:
      - cans-server
    command: python -u -m client ${CANS_DEV_BOB_PUBKEY} ${CANS_DEV_ALICE_PUBKEY}
    env_file:
      - .env
    networks:
      - cans-network

networks:
  cans-network:
    name: cans-network
    driver: bridge
