#!/usr/bin/env bash

. initialize

# Clean-up after any disgraceful shutdown
docker-compose down --remove-orphans

# Start the server
docker-compose up --detach cans-server || { echo "Starting the server failed" && exit 1; }
# Start the echo client
docker-compose up --detach cans-echo-service || { \
    echo "Starting the echo service failed" && docker-compose down && exit 1; \
}

python -m client

docker-compose down
