#!/usr/bin/env bash

# Start the server
docker-compose up --build --detach cans-server || { echo "Starting the server failed" && exit 1; }
# Start the echo client
docker-compose up --build --detach cans-echo-service || { \
    echo "Starting the echo service failed" && docker-compose down && exit 1; \
}
# Start the echo eve
docker-compose up --build --detach cans-echo-eve --remove-orphans  || { \
    echo "Starting the echo eve service failed" && docker-compose down && exit 1; \
}
# Start the echo bob
docker-compose up --build --detach cans-echo-bob --remove-orphans  || { \
    echo "Starting the echo bob service failed" && docker-compose down && exit 1; \
}


echo "Setting up local environment..."
set -a
. ./.env
set +a
# Overwrite the cans-server hostname with localhost
export CANS_SERVER_HOSTNAME=localhost

python -m client

docker-compose down
