#!/usr/bin/env bash

echo "Starting the server container..."
docker-compose up --build --detach cans-server || { echo "Starting the server failed" && exit 1; }
echo "Server started"

echo "Setting up local environment..."
set -a
. ./.env
set +a
# Overwrite the cans-server hostname with localhost
export CANS_SERVER_HOSTNAME=localhost

echo "Running integration tests..."
pytest integration

echo "Stopping the server..."
docker-compose down
echo "All done"
